### PR TITLE
Make AMG thread safe

### PR DESCRIPTION
**Pull request by ranjanan**
Create `nthreads()` scratch spaces.

### CODE REVIEW

**Comment by mohamed82008** [comment]
Would be nice to run a small benchmark to make sure the performance didn't drop for a single thread.

**Comment by ViralBShah** [comment]
Say I have 4 cores, and hence 4 threads, but I spawn 100 solves. Won't those 100 solves be concurrently updating this data structure, unless you schedule the solves to ensure that each processor is only working on one solve at a time?

**Comment by ViralBShah** [comment]
Sorry I accidentally clicked merge. I have reverted it, but you may need to open a new PR. Hope that's ok. I do think that this PR does not fix the issue.

**Comment by ViralBShah** [comment]
Let's continue this discussion in the upstream circuitscape repo.

**Pull request merged**
